# Generated by Django 4.1.7 on 2023-03-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conditions', models.CharField(max_length=255, null=True)),
                ('geo', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
    ]
