# Generated by Django 4.1.7 on 2023-03-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_well'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('well_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.well')),
            ],
        ),
    ]
