# Generated by Django 4.1.2 on 2023-03-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_checks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gazpromuser',
            name='user',
        ),
    ]
